#!/usr/bin/env python3
"""Generate abr_stage2_mlp_shap.ipynb."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "abr_stage2_mlp_shap.ipynb"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Stage 2 MLP SHAP (GradientExplainer, within-cohort CV)\n",
            "\n",
            "This notebook computes out-of-fold (OOF) SHAP values for the synthesis-winning Stage 2 **MLP** on long-format rows (animal × frequency × SPL level).\n",
            "\n",
            "Cohort mapping:\n",
            "- Cohort A (Liberman) → within-cohort scenario **C**\n",
            "- Cohort B (Brad) → within-cohort scenario **A**\n",
            "\n",
            "Outputs:\n",
            "- Parquet: `figures/cache/shap_mlp/`\n",
            "- Figures (PNG + SVG): `figures/shap_mlp/`\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from __future__ import annotations\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from pathlib import Path\n",
            "\n",
            "from utils.benchmark_metrics import apply_slide_rcparams\n",
            "from utils.liberman_classical import liberman_feature_lists, stage2_feature_lists\n",
            "from utils.nn_stage2_data import load_nn_stage2_data, splits_for_long_stage2\n",
            "from utils.stage2_hp import resolve_torch_device\n",
            "from utils.stage2_mlp_shap import (\n",
            "    COHORT_SLUGS_DECK,\n",
            "    compute_fold_shap,\n",
            "    export_feature_names_mlp,\n",
            "    aggregate_oof_long_grain,\n",
            "    aggregate_oof_animal_freq_grain,\n",
            "    export_mlp_shap_parquet,\n",
            "    fit_mlp_fold,\n",
            "    fold_cache_path,\n",
            "    load_fold_cache,\n",
            "    mean_abs_shap_tables_by_cohort,\n",
            "    mlp_hp_for_scenario,\n",
            "    run_mlp_shap_deck_figures,\n",
            "    save_fold_cache,\n",
            ")\n",
            "from utils.stage2_synthesis_cv import (\n",
            "    _mlp_holdout_seed,\n",
            "    attach_global_stage1,\n",
            "    build_cv_scenario_frames,\n",
            "    fit_global_stage1_for_scenario,\n",
            "    generate_cv_folds,\n",
            ")\n",
            "from utils.subject_cv import DEFAULT_CEILING_CV_RANDOM_STATE\n",
            "\n",
            "apply_slide_rcparams()\n",
            "device = resolve_torch_device()\n",
            "print(\"device:\", device)\n",
            "\n",
            "SCENARIO_BY_COHORT = {\"buran\": \"A\", \"liberman\": \"C\"}\n",
            "COHORT_TO_EVAL = {\"buran\": \"Brad\", \"liberman\": \"Liberman\"}\n",
            "\n",
            "N_SPLITS = 10\n",
            "FORCE_RERUN = False\n",
            "MAX_FOLDS = None\n",
            "MAX_BACKGROUND = None  # full training-fold background (per spec)\n",
            "\n",
            "CACHE_DIR = Path(\"figures/cache/shap_mlp\")\n",
            "FIG_DIR = Path(\"figures/shap_mlp\")\n",
            "CACHE_DIR.mkdir(parents=True, exist_ok=True)\n",
            "FIG_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "data = load_nn_stage2_data()\n",
            "splits = splits_for_long_stage2(data)\n",
            "\n",
            "feats = liberman_feature_lists(data.reformatted_orig, data.common_cols)\n",
            "_sn, _sl, _sc, long_num, long_cat = stage2_feature_lists(\n",
            "    feats, noise_label=\"predicted\"\n",
            ")\n",
            "long_log = list(feats[\"long_log\"])\n",
            "\n",
            "feature_names = long_num + list(long_cat) + long_log\n",
            "export_feature_names_mlp(feature_names, cache_dir=CACHE_DIR)\n",
            "\n",
            "global_s1 = {\n",
            "    scen: fit_global_stage1_for_scenario(scen, data, splits, verbose=False)\n",
            "    for scen in (\"A\", \"B\", \"C\")\n",
            "}\n",
            "\n",
            "cohort_outputs: dict[str, dict] = {}\n",
            "\n",
            "for cohort_slug in COHORT_SLUGS_DECK:\n",
            "    eval_cohort = COHORT_TO_EVAL[cohort_slug]\n",
            "    scen = SCENARIO_BY_COHORT[cohort_slug]\n",
            "    hp = mlp_hp_for_scenario(scen)\n",
            "\n",
            "    wide_all = (\n",
            "        data.reformatted.reset_index(drop=True)\n",
            "        if eval_cohort == \"Brad\"\n",
            "        else data.reformatted_orig.reset_index(drop=True)\n",
            "    )\n",
            "    folds = generate_cv_folds(\n",
            "        wide_all, n_splits=N_SPLITS, random_state=DEFAULT_CEILING_CV_RANDOM_STATE\n",
            "    )\n",
            "    n_folds = len(folds) if MAX_FOLDS is None else min(MAX_FOLDS, len(folds))\n",
            "\n",
            "    shap_rows, feat_rows, meta_rows = [], [], []\n",
            "\n",
            "    for fold_id in range(n_folds):\n",
            "        _tr_idx, _te_idx, tr_anim, te_anim = folds[fold_id]\n",
            "\n",
            "        cache_p = fold_cache_path(CACHE_DIR, cohort_slug, fold_id)\n",
            "        if cache_p.is_file() and not FORCE_RERUN:\n",
            "            shap_df, feat_df, meta_df = load_fold_cache(cache_p)\n",
            "        else:\n",
            "            w_tr, w_ev, l_tr, l_ev, _, _ = build_cv_scenario_frames(\n",
            "                eval_cohort, scen, tr_anim, te_anim, data, splits\n",
            "            )\n",
            "            w_tr, w_ev, l_tr, l_ev = attach_global_stage1(\n",
            "                w_tr, w_ev, l_tr, l_ev, global_s1[scen][\"animal_preds\"]\n",
            "            )\n",
            "\n",
            "            holdout_seed = _mlp_holdout_seed(eval_cohort, scen, fold_id)\n",
            "\n",
            "            art = fit_mlp_fold(\n",
            "                l_tr,\n",
            "                l_ev,\n",
            "                long_num,\n",
            "                long_cat,\n",
            "                long_log,\n",
            "                hp,\n",
            "                holdout_seed=holdout_seed,\n",
            "                device=device,\n",
            "            )\n",
            "\n",
            "            shap_df, feat_df = compute_fold_shap(\n",
            "                art,\n",
            "                holdout_seed=holdout_seed,\n",
            "                max_background=MAX_BACKGROUND,\n",
            "            )\n",
            "\n",
            "            meta_df = art.meta_eval.copy()\n",
            "            meta_df[\"fold_id\"] = fold_id\n",
            "            meta_df[\"cohort\"] = cohort_slug\n",
            "            meta_df[\"rmse_animal_freq\"] = art.rmse_animal_freq\n",
            "\n",
            "            save_fold_cache(cache_p, shap_df=shap_df, feat_df=feat_df, meta_df=meta_df)\n",
            "\n",
            "            print(\n",
            "                f\"  {cohort_slug} fold {fold_id}: rows={len(shap_df)} \"\n",
            "                f\"rmse_af={art.rmse_animal_freq:.4f}\"\n",
            "            )\n",
            "\n",
            "        shap_rows.append(shap_df)\n",
            "        feat_rows.append(feat_df)\n",
            "        meta_rows.append(meta_df)\n",
            "\n",
            "    shap_oof = pd.concat(shap_rows, ignore_index=True)\n",
            "    feat_oof = pd.concat(feat_rows, ignore_index=True)\n",
            "    meta_oof = pd.concat(meta_rows, ignore_index=True)\n",
            "\n",
            "    shap_oof, feat_oof, meta_oof = aggregate_oof_long_grain(shap_oof, feat_oof, meta_oof)\n",
            "    cohort_outputs[cohort_slug] = {\"shap\": shap_oof, \"feat\": feat_oof, \"meta\": meta_oof}\n",
            "    export_mlp_shap_parquet(cohort_slug, shap_oof, feat_oof, meta_oof, cache_dir=CACHE_DIR)\n",
            "    print(\"exported\", cohort_slug, \"rows\", len(meta_oof))\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "COHORT_DISPLAY = {\"liberman\": \"Cohort A (Liberman)\", \"buran\": \"Cohort B (Brad)\"}\n",
            "\n",
            "# Mean |SHAP| at animal × frequency (SPL levels averaged within each pair).\n",
            "tables = mean_abs_shap_tables_by_cohort(cohort_outputs, grain=\"animal_freq\")\n",
            "for slug in COHORT_SLUGS_DECK:\n",
            "    tbl = tables[slug]\n",
            "    shap_af, _, _ = aggregate_oof_animal_freq_grain(\n",
            "        cohort_outputs[slug][\"shap\"],\n",
            "        cohort_outputs[slug][\"feat\"],\n",
            "        cohort_outputs[slug][\"meta\"],\n",
            "    )\n",
            "    assert tbl[\"mean_abs_shap\"].is_monotonic_decreasing\n",
            "    assert tbl[\"rank\"].iloc[0] == 1\n",
            "    print(\n",
            "        f\"{COHORT_DISPLAY[slug]}  \"\n",
            "        f\"(n_animal_freq_rows={len(shap_af):,}; mean |SHAP| pooled over SPL)\"\n",
            "    )\n",
            "    display(\n",
            "        tbl.assign(mean_abs_shap=lambda d: d[\"mean_abs_shap\"].map(\"{:.5f}\".format))\n",
            "    )\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "paths = run_mlp_shap_deck_figures(cohort_outputs, FIG_DIR)\n",
            "print(\"wrote\", len(paths), \"figure files to\", FIG_DIR)\n",
        ],
    },
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB.write_text(json.dumps(nb, indent=1) + "\n", encoding="utf-8")
print("Wrote", NB)