#!/usr/bin/env python3
"""Generate abr_stage2_mlp_shap.ipynb."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "abr_stage2_mlp_shap.ipynb"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Stage 2 MLP SHAP (GradientExplainer, within-cohort CV)\n",
            "\n",
            "Out-of-fold SHAP for the synthesis-winning **MLP** on **long** rows "
            "(animal × frequency × SPL level). Brad = scenario **A**; Liberman = scenario **C**.\n",
            "\n",
            "1. OOF SHAP (10-fold subject CV, fold cache)\n",
            "2. Parquet export\n",
            "3. Figures (`figures/shap/mlp/`)\n",
            "\n",
            "**Prerequisites:** `figures/cache/stage2_best_hp/A.json` and `C.json` "
            "(from `abr_stage2_hp_tuning.ipynb`).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from __future__ import annotations\n",
            "\n",
            "from pathlib import Path\n",
            "\n",
            "import pandas as pd\n",
            "\n",
            "from utils.benchmark_metrics import STAGE2_BEST_HP_DIR, apply_slide_rcparams\n",
            "from utils.liberman_classical import liberman_feature_lists, stage2_feature_lists\n",
            "from utils.nn_stage2_data import load_nn_stage2_data, splits_for_long_stage2\n",
            "from utils.stage2_hp import resolve_torch_device\n",
            "from utils.stage2_mlp_shap import (\n",
            "    build_long_feature_annotation_table,\n",
            "    compute_fold_shap,\n",
            "    fit_mlp_fold,\n",
            "    fold_cache_path,\n",
            "    load_fold_cache,\n",
            "    mlp_hp_for_scenario,\n",
            "    run_mlp_shap_plots,\n",
            "    save_fold_cache,\n",
            ")\n",
            "from utils.stage2_synthesis_cv import (\n",
            "    _mlp_holdout_seed,\n",
            "    attach_global_stage1,\n",
            "    build_cv_scenario_frames,\n",
            "    fit_global_stage1_for_scenario,\n",
            "    generate_cv_folds,\n",
            ")\n",
            "from utils.subject_cv import DEFAULT_CEILING_CV_RANDOM_STATE\n",
            "\n",
            "SCENARIO_BY_COHORT = {\"buran\": \"A\", \"liberman\": \"C\"}\n",
            "COHORT_TO_EVAL = {\"buran\": \"Brad\", \"liberman\": \"Liberman\"}\n",
            "N_SPLITS = 10\n",
            "FORCE_RERUN = False\n",
            "CACHE_DIR = Path(\"figures/cache/shap/mlp\")\n",
            "FIG_DIR = Path(\"figures/shap/mlp\")\n",
            "CACHE_DIR.mkdir(parents=True, exist_ok=True)\n",
            "FIG_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "for scen in (\"A\", \"C\"):\n",
            "  mlp_hp_for_scenario(scen)\n",
            "\n",
            "device = resolve_torch_device()\n",
            "apply_slide_rcparams()\n",
            "print(\"device:\", device)\n",
            "print(\"HP dir:\", STAGE2_BEST_HP_DIR)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import shap\n",
            "\n",
            "print(\"shap version:\", shap.__version__)\n",
            "\n",
            "data = load_nn_stage2_data()\n",
            "splits = splits_for_long_stage2(data)\n",
            "feats = liberman_feature_lists(data.reformatted_orig, data.common_cols)\n",
            "_sn, _sl, _sc, long_num, long_cat = stage2_feature_lists(\n",
            "    feats, noise_label=\"predicted\"\n",
            ")\n",
            "long_log = list(feats[\"long_log\"])\n",
            "feature_names_df = build_long_feature_annotation_table(\n",
            "    long_num + list(long_cat) + long_log\n",
            ")\n",
            "\n",
            "global_s1 = {\n",
            "    scen: fit_global_stage1_for_scenario(scen, data, splits, verbose=False)\n",
            "    for scen in (\"A\", \"B\", \"C\")\n",
            "}\n",
            "\n",
            "cohort_outputs: dict[str, dict] = {}\n",
            "\n",
            "for cohort_slug, eval_cohort in COHORT_TO_EVAL.items():\n",
            "    scen = SCENARIO_BY_COHORT[cohort_slug]\n",
            "    hp = mlp_hp_for_scenario(scen)\n",
            "    wide_all = (\n",
            "        data.reformatted.reset_index(drop=True)\n",
            "        if eval_cohort == \"Brad\"\n",
            "        else data.reformatted_orig.reset_index(drop=True)\n",
            "    )\n",
            "    folds = generate_cv_folds(\n",
            "        wide_all, n_splits=N_SPLITS, random_state=DEFAULT_CEILING_CV_RANDOM_STATE\n",
            "    )\n",
            "    shap_rows, feat_rows, meta_rows = [], [], []\n",
            "\n",
            "    for fold_id, (_tr_idx, _te_idx, tr_anim, te_anim) in enumerate(folds):\n",
            "        cache_p = fold_cache_path(CACHE_DIR, cohort_slug, fold_id)\n",
            "        if cache_p.is_file() and not FORCE_RERUN:\n",
            "            shap_df, feat_df, meta_df = load_fold_cache(cache_p)\n",
            "        else:\n",
            "            w_tr, w_ev, l_tr, l_ev, _, _ = build_cv_scenario_frames(\n",
            "                eval_cohort, scen, tr_anim, te_anim, data, splits\n",
            "            )\n",
            "            w_tr, w_ev, l_tr, l_ev = attach_global_stage1(\n",
            "                w_tr, w_ev, l_tr, l_ev, global_s1[scen][\"animal_preds\"]\n",
            "            )\n",
            "            holdout_seed = _mlp_holdout_seed(eval_cohort, scen, fold_id)\n",
            "            art = fit_mlp_fold(\n",
            "                l_tr, l_ev, long_num, long_cat, long_log, hp,\n",
            "                holdout_seed=holdout_seed, device=device,\n",
            "            )\n",
            "            shap_df, feat_df = compute_fold_shap(art, holdout_seed=holdout_seed)\n",
            "            meta_df = art.meta_eval.copy()\n",
            "            meta_df[\"fold_id\"] = fold_id\n",
            "            meta_df[\"cohort\"] = cohort_slug\n",
            "            meta_df[\"rmse_animal_freq\"] = art.rmse_animal_freq\n",
            "            save_fold_cache(cache_p, shap_df=shap_df, feat_df=feat_df, meta_df=meta_df)\n",
            "            print(\n",
            "                f\"  {cohort_slug} fold {fold_id}: rows={len(shap_df)} \"\n",
            "                f\"rmse_af={art.rmse_animal_freq:.4f}\"\n",
            "            )\n",
            "\n",
            "        shap_rows.append(shap_df)\n",
            "        feat_rows.append(feat_df)\n",
            "        meta_rows.append(meta_df)\n",
            "\n",
            "    shap_oof = pd.concat(shap_rows, ignore_index=True)\n",
            "    feat_oof = pd.concat(feat_rows, ignore_index=True)\n",
            "    meta_oof = pd.concat(meta_rows, ignore_index=True)\n",
            "\n",
            "    n_af = meta_oof.groupby([\"animal_id\", \"frequency\"]).ngroups\n",
            "    print(\n",
            "        cohort_slug,\n",
            "        \"long_rows=\", len(meta_oof),\n",
            "        \"animals=\", meta_oof[\"animal_id\"].nunique(),\n",
            "        \"animal_freq_pairs=\", n_af,\n",
            "        \"levels=\", sorted(meta_oof[\"level\"].dropna().unique().tolist()),\n",
            "    )\n",
            "    cohort_outputs[cohort_slug] = {\n",
            "        \"shap\": shap_oof,\n",
            "        \"feat\": feat_oof,\n",
            "        \"meta\": meta_oof,\n",
            "    }\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "feature_names_df.to_parquet(CACHE_DIR / \"feature_names.parquet\", index=False)\n",
            "\n",
            "for cohort_slug, payload in cohort_outputs.items():\n",
            "    shap_df = payload[\"shap\"].copy()\n",
            "    meta_df = payload[\"meta\"].copy()\n",
            "    shap_export_features = shap_df.rename(\n",
            "        columns={\"frequency\": \"frequency_feature\", \"level\": \"level_feature\"}\n",
            "    )\n",
            "    shap_export = pd.concat(\n",
            "        [meta_df[[\"animal_id\", \"frequency\", \"level\"]], shap_export_features],\n",
            "        axis=1,\n",
            "    )\n",
            "    shap_export.to_parquet(CACHE_DIR / f\"shap_values_{cohort_slug}.parquet\", index=False)\n",
            "    meta_export = meta_df[\n",
            "        [\n",
            "            c\n",
            "            for c in [\n",
            "                \"animal_id\",\n",
            "                \"frequency\",\n",
            "                \"level\",\n",
            "                \"noise_cat\",\n",
            "                \"noise_preds\",\n",
            "                \"synapses\",\n",
            "                \"fold_id\",\n",
            "                \"cohort\",\n",
            "                \"experimental_group\",\n",
            "                \"tx\",\n",
            "            ]\n",
            "            if c in meta_df.columns\n",
            "        ]\n",
            "    ].copy()\n",
            "    meta_export.to_parquet(\n",
            "        CACHE_DIR / f\"shap_metadata_{cohort_slug}.parquet\", index=False\n",
            "    )\n",
            "    print(\"exported\", cohort_slug, len(meta_export), \"rows\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "for cohort_slug, payload in cohort_outputs.items():\n",
            "    run_mlp_shap_plots(\n",
            "        payload[\"shap\"],\n",
            "        payload[\"feat\"],\n",
            "        payload[\"meta\"],\n",
            "        cohort_slug,\n",
            "        FIG_DIR,\n",
            "    )\n",
            "    print(\"figures written to\", FIG_DIR)\n",
        ],
    },
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB.write_text(json.dumps(nb, indent=1) + "\n", encoding="utf-8")
print("Wrote", NB)
